version: '3.9'

services:
  {{ role_name }}:
    image: google/cadvisor
    hostname: "{% raw %}{{.Service.Name}}_{{.Task.Slot}}{% endraw %}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
# WARNING: host devices are not supported by docker swarm yet
#    device:
#      - /dev/kmsg
    networks: {{ stacks[stack_name][role_name]['networks'] | list }}
    extra_hosts: {{ stacks[stack_name][role_name]['extra_hosts'] }}
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M

networks: {{ stacks[stack_name][role_name]['networks'] }}