version: '3.9'

services:
  {{ role_name }}:
    image: {{ images[stack_name][role_name] }}
    hostname: "{%raw%}{{.Service.Name}}_{{.Task.Slot}}{%endraw%}"
    environment: {{ stacks[stack_name][role_name]['env_vars'] | to_json }}
#    ports:
#      - 8089:8081
    deploy:
      mode: replicated
      replicas: {{ stacks[stack_name][role_name]['replicas'] | default (1) }}
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
{% if stacks[stack_name][role_name]['placement'] is defined %}
      placement:
        constraints: [node.labels.name == {{ stacks[stack_name][role_name]['placement'] }}]
{% endif %}
      update_config:
        parallelism: 1
        delay: 2s
        order: start-first
        failure_action: rollback
        monitor: 20s
      rollback_config:
        parallelism: 1
        delay: 10s
    command: taskmanager
    healthcheck:
      test: ["CMD-SHELL","curl -fs -o /dev/null http://localhost:9999"]
      interval: 10s
      timeout: 2s
      retries: 10
    configs:
      - source: ap-main-ext.properties
        target: /opt/domain/ap/conf/flink-task/ap-main-ext.properties
    networks: {{ stacks[stack_name][role_name]['networks'] | list }}
    extra_hosts: {{ stacks[stack_name][role_name]['extra_hosts'] }}
    volumes:
      - /etc/localtime:/etc/localtime:ro

configs:
  ap-main-ext.properties:
    name: {{ config_files['ap-main-ext.properties']['name'] }}
    external: true

networks: {{ stacks[stack_name][role_name]['networks'] }}
