version: '3.9'

services:
  {{ role_name }}:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: "{% raw %}{{.Service.Name}}_{{.Task.Slot}}{% endraw %}"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
#      ZOO_MY_ID: "{% raw %}{{.Task.Slot}}+1{% endraw %}"
#      ZOO_SERVERS: {% for i in range(stacks[stack_name][role_name]['replicas']) %}server.{{i+1}}={% raw %}{{.Service.Name}}{% endraw %}_{{i+1}}:2888:3888 {% endfor %}

    deploy:
      mode: replicated
      replicas: {{ stacks[stack_name][role_name]['replicas'] | default (1) }}
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.fstype == glusterfs
{% if stacks[stack_name][role_name]['placement'] is defined %}
          - node.labels.name == {{ stacks[stack_name][role_name]['placement'] }}
{% endif %}
      update_config:
        parallelism: 1
        delay: 2s
        order: start-first
        failure_action: rollback
        monitor: 20s
      rollback_config:
        parallelism: 1
        delay: 10s
    networks: {{ stacks[stack_name][role_name]['networks'] | list }}
    extra_hosts: {{ stacks[stack_name][role_name]['extra_hosts'] }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{ domain_volumes }}/{{ stack_name }}/{{ role_name }}/data:/bitnami

networks: {{ stacks[stack_name][role_name]['networks'] }}

#volumes:
#  zookeeper:
#    name: 'zookeeper'
#    name: '{% raw %}{{.Service.Name}}_{{.Task.Slot}}{% endraw %}'
