IMAGE: someimage2
JAVA_OPTS: -Dss.mode=streamer
           -Dssc.mongo=mongodb://mongo-ssc:27017/ssc
           -Dhttp.port=8080
           -Dssr.db=mongodb://mongo-ssr:27017/ssr
           -Dlogback.configurationFile=logback.xml
           -Dlogger.resource=logback.xml
           -Dssc.rabbitmq.amq=ssc:ssc@rabbitmq:5672/stat-server.topic/monitoring.statServerEvents.amq-client/monitoring.statServerEvents.#
           -Dapp.external.update.period=24
           -Dakka.remote.netty.tcp.hostname=ssc
           -Dakka.remote.netty.tcp.port=2552
           -Dakka.remote.netty.tcp.bind-hostname=0.0.0.0
           -Dakka.remote.netty.tcp.bind-port=2552
#           -Dssc.akka=ssc:2552
#           -Dssrc.akka=ssrc:2552
#           -Dapp.integration.enabled=true
#           -Dapp.url=http://app:8080
#           -Dapp.login=admin
#           -Dapp.password=uWJ6miT9DvsvCvR
#           -Dapp.sendCameraStatusInAnyCase=false
#           -Dssc.events.size=2
#           -Dssr.events.size=2
#           -Dcamerastatus.rabbitmq=ssc:ssc@rabbitmq:5672/ss-mw.topic/ss-mw/#
#DB_URI: mongodb://mongo-ssr:27017/ssr
