---
- name: Creat directory for a docker repository public key
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
  become: yes

- name: Download docker repository public key
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg'
  args:
    warn: false
  become: yes

- name: Adding docker repository to apt sources
  shell: 'echo
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'
  become: yes

- name: Run apt-get update
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install docker packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-docker
      - python3-jsondiff
    update_cache: yes
  become: yes

- name: Get non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_user_id }}"
  tags:
    - clean

- name: Add existing user '{{ remote_regular_user }}' to group docker
  user:
    name: '{{ remote_regular_user }}'
    groups: docker
    append: yes
  become: yes

- name: Enable and start docker
  ansible.builtin.systemd:
    name: docker.service
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: Log into Netris DockerHub
  docker_login:
    registry: docker-hub.domain.ru
    username: domain
    password: qweasd123

- name: Disable and stop docker
  ansible.builtin.systemd:
    name: docker.service
    enabled: false
    state: stopped
  become: yes
  ignore_errors: true
  tags:
    - never
    - clean

- name: Remove user '{{ remote_regular_user }}' from group docker
  user:
    name: '{{ remote_regular_user }}'
    groups: docker
    append: no
  become: yes
  tags:
    - never
    - clean

- name: Remove docker packages
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - python3-docker
    - python3-jsondiff
    state: absent
    purge: yes
  become: yes
  tags:
    - never
    - clean

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
  become: yes
  tags:
    - clean
    - never

- name: Remove directory with gpg key
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: absent
  become: yes
  tags:
    - clean
    - never

- name: Remove docker repository from apt sources
  ansible.builtin.file:
    path: '/etc/apt/sources.list.d/docker.list'
    state: absent
  become: yes
  tags:
    - clean
    - never
