route:
  receiver: 'telegram'
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1d

receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token: '54038493854:AJLKGJ(*&)#(*#%$JLKDJFKLJDF'
      chat_id: -1000000000000000000000
      api_url: 'https://api.telegram.org'
      parse_mode: ''
