version: '3.2'

services:
  {{ role_name }}:
    image: portainer/portainer-ce:2.16.2
    command: -H tcp://tasks.{{ role_name }}_agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9009:9000"
      - "8000:8000"
    volumes:
      - {{ domain_volumes }}/{{ stack_name }}/{{ role_name }}/data:/data
    networks:
      - {{ role_name}}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.fstype == glusterfs]

  {{ role_name }}_agent:
    image: portainer/agent:2.16.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - {{ role_name}}
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  {{ role_name }}:
    driver: overlay
    attachable: true

#volumes:
#  portainer_data:
