---
- name: Add Workers to the Swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ hostvars['localhost']['worker_token']['stdout'] }}"
    remote_addrs: [ "{{ hostvars['localhost']['leader'] }}:2377" ]
  tags: swarm

#- debug:
#    msg: "{{groups['leader'][0]}} {{hostvars['localhost']['leader']}}"
